### ISSUE TITLE
`/jupyter.sh` launched window that needed token - expected?

### ISSUE THREAD

**Issue by david-bakin** [ianhellstrom/zoose#18]
I'm not exactly sure what the ["traditional Jupyterlab experience"](https://databaseline.tech/zoose-3.0/#or-the-jupyterlab-experience) is, but perhaps it means that when the browser is launched via `/jupyter.sh` you still have to find and copy/paste the token in to the auth screen?  (I did that, and it worked, copying the token from one of the given urls.)

None of the three suggested ways to access the server actually worked, BTW:

```
[C 2022-10-17 20:40:28.682 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/gitpod/.local/share/jupyter/runtime/jpserver-2207-open.html
    Or copy and paste one of these URLs:
        http://davidbakin-zooseplaypen-lv7b3xp10i4:8888/lab?token=6db29cd2ba64eb918fff6bf1b3d8dd12eae38015d0145f1f
     or http://127.0.0.1:8888/lab?token=6db29cd2ba64eb918fff6bf1b3d8dd12eae38015d0145f1f
```

They all gave some sort of 404.

I guess the issue here is that ... I've got no Jupyter experience.  It was easy to figure out the token from the given urls so I could cut/paste it.  But the three urls didn't work.  

(BTW, good job on this repo! It really is a seamless way to get going.  Only thing I could suggest at this point as a feature request would be an "import" that took a URL to a notebook - cloning it, I suppose - not just a local filesystem name.)

**Comment by ianhellstrom** [comment]
The token is entirely expected and that gives you the JupyterLab UX. 

The URLs are generated by Jupyter and they assume a local instance, i.e. your computer, not a cloud-based instance. Hence, the 127.0.0.1 IP. I doubt I can do much about it, but I’ll check.

Note that these links work if you run Zoose locally, i.e. with Docker.

**Comment by ianhellstrom** [comment]
If you update the Gitpod image to 3.0.1, the problem should vanish. See: https://github.com/ianhellstrom/zoose-gitpod/blob/master/.gitpod.yml#L1

You can click the pop-up in Gitpod when running `/jupyter.sh` and it immediately leads to a JupyterLab notebook without the need to enter a password or copy-paste a token from the CLI.
